---
abstract: 'Notification queue for Zabbix, Nagios, et.al.'
author:
  - 'Dominik Schulz <tex@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.06
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Monitoring-Spooler
requires:
  Config::Yak: 0
  DBD::SQLite: 0
  DBI: 0
  File::ShareDir: 0
  File::Temp: 0
  HTTP::Cookies: 0
  IPC::Open2: 0
  JSON: 0
  LWP::UserAgent: 0
  Log::Tree: 0
  Log::Tree::RequiredLogger: 0
  Module::Pluggable::Object: 0
  Moose: 0
  MooseX::App::Cmd: 0
  MooseX::App::Cmd::Command: 0
  Plack::Builder: 0
  Plack::Loader: 0
  Plack::Request: 0
  Proc::ProcessTable: 0
  SMS::Send: 0
  Template: 0
  Try::Tiny: 0
  URI::Escape: 0
  XMLRPC::Lite: 0
  feature: 0
  lib: 0
  mro: 0
  namespace::autoclean: 0
  perl: 5.010_000
  strict: 0
  warnings: 0
version: 0.05
x_authority: cpan:TEX
